# Generated by Django 5.0.4 on 2024-04-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0002_hotel_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climate',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='climate',
            field=models.ManyToManyField(related_name='countries', to='touragency.climate'),
        ),
    ]
