# Generated by Django 5.0.4 on 2024-04-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0003_remove_climate_country_country_climate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='climate',
            field=models.CharField(max_length=255),
        ),
    ]
