# Generated by Django 5.0.4 on 2024-04-29 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0006_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('discount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='UsedDiscounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='touragency.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
