# Generated by Django 5.0.4 on 2024-04-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0007_promocode_order_promocode_useddiscounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='trips',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
