# Generated by Django 5.0.4 on 2024-04-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0009_remove_order_promocode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Term',
            new_name='FAQ',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=120),
        ),
    ]
