# Generated by Django 5.0.4 on 2024-04-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0010_rename_term_faq_remove_article_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='published_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='date_added',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
