# Generated by Django 5.0.4 on 2024-04-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0011_rename_published_date_article_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(default=1, upload_to='images/logo1'),
            preserve_default=False,
        ),
    ]
