# Generated by Django 5.0.4 on 2024-04-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0012_companyinfo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
