# Generated by Django 5.0.4 on 2024-04-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0015_user_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
