# Generated by Django 5.0.4 on 2024-04-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0016_delete_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='title',
        ),
    ]
