# Generated by Django 5.0.4 on 2024-05-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0019_article_image_contact_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Terrible'), (2, 'Poor'), (3, 'Average'), (4, 'Very Good'), (5, 'Excellent')], default=3),
        ),
    ]
