# Generated by Django 5.0.4 on 2024-05-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0020_alter_hotel_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
