# Generated by Django 5.0.4 on 2024-05-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0021_alter_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='touragency.tour'),
        ),
    ]
