# Generated by Django 5.0.4 on 2024-05-01 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0022_alter_order_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 2, 1, 1, 7, 420546)),
        ),
    ]
