# Generated by Django 5.0.4 on 2024-05-02 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0027_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 2, 0, 18, 20, 816727, tzinfo=datetime.timezone.utc)),
        ),
    ]
