# Generated by Django 5.0.4 on 2024-05-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0028_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(),
        ),
    ]
