# Generated by Django 5.0.4 on 2024-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0029_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('logo', models.ImageField(upload_to='images/')),
                ('link', models.URLField()),
            ],
        ),
    ]
