# Generated by Django 5.0.4 on 2024-09-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touragency', '0030_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='photo',
            field=models.ImageField(default=111, upload_to='images/'),
            preserve_default=False,
        ),
    ]
